#!/bin/bash
# Railway 컨테이너 진입점 (Claude-code 서버)
# 설계 (B 모드 — 수동 qarko-init):
#   - SSH 호스트 키/비밀번호 준비
#   - Railway env → SSH 세션 전파 (root:claude 640)
#   - dev-env-backup 사전 clone/pull (smoke-test 등 접근 가능하게)
#   - MOTD: SSH 로그인 시 수동 실행 순서 안내
#   - sshd foreground 실행 (tini PID 1 자식)
#
# 사장님 SSH 접속 후 순서:
#   1. gh auth login
#   2. railway login
#   3. qarko-init
#   4. tmux attach -t main
#   5. ~/start-claude.sh
#   6. "재시작"

set -eo pipefail

log() { echo "[entrypoint] $*"; }

# ── 1. SSH host key 생성 (런타임 → 배포마다 고유) ────────────────────────
if ! ls /etc/ssh/ssh_host_*_key >/dev/null 2>&1; then
    ssh-keygen -A >/dev/null 2>&1 && log "SSH host keys generated."
fi

# ── 2. SSH 비밀번호 주입 + 이중 검증 ─────────────────────────────────────
if [ -n "${SSH_ROOT_PASSWORD:-}" ]; then
    echo "root:${SSH_ROOT_PASSWORD}" | chpasswd
    if grep -qE '^root:[!*:]' /etc/shadow || grep -qE '^root::' /etc/shadow; then
        log "FATAL: chpasswd root silently failed."
        exit 1
    fi
    log "root SSH password set."
else
    passwd -l root >/dev/null 2>&1
    if ! grep -q '^root:!' /etc/shadow; then
        log "FATAL: failed to lock root account; aborting."
        exit 1
    fi
    log "SSH_ROOT_PASSWORD not set — root account locked."
fi

if [ -n "${SSH_CLAUDE_PASSWORD:-}" ]; then
    echo "claude:${SSH_CLAUDE_PASSWORD}" | chpasswd
    if grep -qE '^claude:[!*:]' /etc/shadow || grep -qE '^claude::' /etc/shadow; then
        log "FATAL: chpasswd claude silently failed."
        exit 1
    fi
    log "claude SSH password set."
else
    passwd -l claude >/dev/null 2>&1
    if ! grep -q '^claude:!' /etc/shadow; then
        log "FATAL: failed to lock claude account; aborting."
        exit 1
    fi
    log "SSH_CLAUDE_PASSWORD not set — claude account locked."
fi

# ── 3. Railway env → SSH 세션 전달 (640 root:claude) ─────────────────────
ENV_FILE="/etc/profile.d/qarko-railway-env.sh"
{
    echo "# Generated by entrypoint.sh at $(date -Iseconds) — DO NOT EDIT"
    env \
        | grep -E '^(RAILWAY_|DISCORD_|TELEGRAM_|GITHUB_|HERMES_|OPENROUTER_|ANTHROPIC_|CLAUDE_)[A-Z0-9_]+=' \
        | grep -v -E '^(SSH_ROOT_PASSWORD|SSH_CLAUDE_PASSWORD)=' \
        | sed 's/^/export /' \
        || true
} > "$ENV_FILE"
chown root:claude "$ENV_FILE"
chmod 640 "$ENV_FILE"
log "Railway env exported to $ENV_FILE (mode 640, root:claude)"

# ── 4. /home/claude 소유권 보정 (첫 부팅 볼륨 대응) ──────────────────────
if [ "$(stat -c %U /home/claude 2>/dev/null)" != "claude" ]; then
    chown -R claude:claude /home/claude 2>/dev/null \
        && log "Fixed /home/claude ownership to claude." \
        || log "WARN: chown /home/claude failed."
fi

# ── 5. qarko-init 로그 디렉토리 (사장님 수동 실행 시 사용) ───────────────
INIT_DIR="/home/claude/.qarko-init"
install -d -o claude -g claude -m 755 "$INIT_DIR"

# ── 6. dev-env-backup 사전 clone/pull ────────────────────────────────────
# 빈 볼륨 첫 부팅 시에도 smoke-test / restore.sh 에 즉시 접근 가능.
# 인증: Railway env 의 GITHUB_TOKEN 으로 URL embed (일회성, clone 후 token 제거).
BACKUP_REPO_DIR="/home/claude/dev-env-backup"
git config --global --add safe.directory "$BACKUP_REPO_DIR" 2>/dev/null || true

# git-credentials 파일: 사장님 gh auth login 전에도 restore.sh 의 git pull 동작 가능하게.
# gh auth login 이후엔 gh 가 별도 credential helper 로 덮어씀 (영향 없음).
if [ -n "${GITHUB_TOKEN:-}" ]; then
    install -o claude -g claude -m 600 /dev/null /home/claude/.git-credentials
    echo "https://x-access-token:${GITHUB_TOKEN}@github.com" \
        > /home/claude/.git-credentials
    chown claude:claude /home/claude/.git-credentials
    sudo -u claude git config --global credential.helper store 2>/dev/null || true
fi

(
    set +eo pipefail
    if [ -z "${GITHUB_TOKEN:-}" ]; then
        echo "[pre] WARN: GITHUB_TOKEN 없음 — pre-clone 생략"
        exit 0
    fi
    if [ ! -d "$BACKUP_REPO_DIR/.git" ]; then
        echo "[pre] cloning dev-env-backup"
        git clone --depth=50 \
            "https://x-access-token:${GITHUB_TOKEN}@github.com/qarko/dev-env-backup.git" \
            "$BACKUP_REPO_DIR"
        git -C "$BACKUP_REPO_DIR" remote set-url origin \
            https://github.com/qarko/dev-env-backup.git
        chown -R claude:claude "$BACKUP_REPO_DIR"
        echo "[pre] clone OK"
    else
        echo "[pre] updating dev-env-backup to origin/main"
        git -C "$BACKUP_REPO_DIR" remote set-url origin \
            "https://x-access-token:${GITHUB_TOKEN}@github.com/qarko/dev-env-backup.git"
        git -C "$BACKUP_REPO_DIR" fetch --quiet origin main
        git -C "$BACKUP_REPO_DIR" reset --hard origin/main
        git -C "$BACKUP_REPO_DIR" remote set-url origin \
            https://github.com/qarko/dev-env-backup.git
        chown -R claude:claude "$BACKUP_REPO_DIR"
        echo "[pre] update OK"
    fi
) >>"$INIT_DIR/pre-clone.log" 2>&1 \
    && log "dev-env-backup 준비 완료 (로그: $INIT_DIR/pre-clone.log)" \
    || log "WARN: dev-env-backup pre-clone/pull 실패 (로그: $INIT_DIR/pre-clone.log)"

# smoke-test 편의 심볼릭 링크 (~ 에서 바로 실행)
if [ -f "$BACKUP_REPO_DIR/smoke-test.sh" ] && [ ! -e /home/claude/smoke-test.sh ]; then
    ln -sf "$BACKUP_REPO_DIR/smoke-test.sh" /home/claude/smoke-test.sh
    chown -h claude:claude /home/claude/smoke-test.sh
fi

# ── 7. MOTD: 사장님 SSH 로그인 시 실행 순서 안내 ────────────────────────
cat > /etc/profile.d/qarko-welcome.sh <<'EOS'
# qarko Claude-code 서버 환영 메시지 + 수동 실행 순서
if [ -t 0 ] && [ -t 1 ] && [ "$USER" = "claude" ] && [ -z "${QARKO_WELCOME_SHOWN:-}" ]; then
    export QARKO_WELCOME_SHOWN=1
    cat <<'MSG'
════════════════════════════════════════════════════════
  qarko Claude-code 서버 (재배포 후 수동 실행 순서)
════════════════════════════════════════════════════════
  1. gh auth login        # GitHub 로그인
  2. railway login        # Railway 로그인
  3. qarko-init           # 환경 복원 (18 step)
  4. tmux attach -t main
  5. ~/start-claude.sh    # Claude Code 시작
  6. "재시작" 입력        # 직전 30턴 복원

  상태 확인 : bash ~/smoke-test.sh
  로그      : ls -lt ~/.qarko-init/logs/
════════════════════════════════════════════════════════
MSG
fi
EOS
chmod 644 /etc/profile.d/qarko-welcome.sh

# ── 8. sshd foreground — tini(PID 1)의 자식, sshd가 자기 자식 reap ───────
log "sshd starting in foreground on :22."
exec /usr/sbin/sshd -D -e
