#!/bin/bash
# Railway 컨테이너 진입점 (Claude-code 서버)
# 역할:
#   - SSH 호스트 키/비밀번호 준비
#   - Railway env → SSH 세션 전파 (root:claude 640)
#   - 이미지 업데이트 또는 첫 부팅 시 qarko-init 백그라운드 자동 실행
#   - sshd foreground 실행 (tini PID 1의 자식)

set -eo pipefail

log() { echo "[entrypoint] $*"; }

# ── 1. SSH host key 생성 (이미지 아닌 런타임 → 배포마다 고유) ────────────
if ! ls /etc/ssh/ssh_host_*_key >/dev/null 2>&1; then
    ssh-keygen -A >/dev/null 2>&1 && log "SSH host keys generated."
fi

# ── 2. SSH 비밀번호 주입 (환경변수 기반) + 이중 검증 ─────────────────────
# 검증 로직: /etc/shadow 두번째 필드가 '!'/'*'/빈 값이 아니면 비밀번호 설정 완료
if [ -n "${SSH_ROOT_PASSWORD:-}" ]; then
    echo "root:${SSH_ROOT_PASSWORD}" | chpasswd
    if grep -qE '^root:[!*:]' /etc/shadow || grep -qE '^root::' /etc/shadow; then
        log "FATAL: chpasswd root silently failed (shadow still locked/empty)."
        exit 1
    fi
    log "root SSH password set."
else
    passwd -l root >/dev/null 2>&1
    if ! grep -q '^root:!' /etc/shadow; then
        log "FATAL: failed to lock root account; aborting."
        exit 1
    fi
    log "SSH_ROOT_PASSWORD not set — root account locked."
fi

if [ -n "${SSH_CLAUDE_PASSWORD:-}" ]; then
    echo "claude:${SSH_CLAUDE_PASSWORD}" | chpasswd
    if grep -qE '^claude:[!*:]' /etc/shadow || grep -qE '^claude::' /etc/shadow; then
        log "FATAL: chpasswd claude silently failed."
        exit 1
    fi
    log "claude SSH password set."
else
    passwd -l claude >/dev/null 2>&1
    if ! grep -q '^claude:!' /etc/shadow; then
        log "FATAL: failed to lock claude account; aborting."
        exit 1
    fi
    log "SSH_CLAUDE_PASSWORD not set — claude account locked."
fi

# ── 3. Railway env → SSH 세션 전달 (root:claude 640) ─────────────────────
# SSH 로그인 shell이 읽어야 하므로 claude 그룹에 read 권한. 다른 사용자는 차단.
# pipefail 보호: 매치 없을 때 grep 이 exit 1 → `|| true` 로 방어.
ENV_FILE="/etc/profile.d/qarko-railway-env.sh"
{
    echo "# Generated by entrypoint.sh at $(date -Iseconds) — DO NOT EDIT"
    env \
        | grep -E '^(RAILWAY_|DISCORD_|TELEGRAM_|GITHUB_|HERMES_|OPENROUTER_|ANTHROPIC_|CLAUDE_)[A-Z0-9_]+=' \
        | grep -v -E '^(SSH_ROOT_PASSWORD|SSH_CLAUDE_PASSWORD)=' \
        | sed 's/^/export /' \
        || true
} > "$ENV_FILE"
chown root:claude "$ENV_FILE"
chmod 640 "$ENV_FILE"
log "Railway env exported to $ENV_FILE (mode 640, root:claude)"

# ── 4. /home/claude 소유권 보정 (볼륨이 root로 마운트되는 첫 부팅 대응) ──
if [ "$(stat -c %U /home/claude 2>/dev/null)" != "claude" ]; then
    chown -R claude:claude /home/claude 2>/dev/null \
        && log "Fixed /home/claude ownership to claude." \
        || log "WARN: chown /home/claude failed."
fi

# ── 5. qarko-init 자동 실행 (이미지 ID 기반 flag) ───────────────────────
# 이미지 ID 우선순위: RAILWAY_GIT_COMMIT_SHA > /etc/qarko-image-id > "unknown".
# Railway는 배포 시 RAILWAY_GIT_COMMIT_SHA 자동 주입 → 커밋 단위 재실행이 정확한 의미.
IMAGE_ID="${RAILWAY_GIT_COMMIT_SHA:-$(cat /etc/qarko-image-id 2>/dev/null || echo unknown)}"
INIT_DIR="/home/claude/.qarko-init"
INIT_FLAG="$INIT_DIR/init-complete"
LOCK_FILE="$INIT_DIR/init.lock"
STATUS_FILE="$INIT_DIR/status"

install -d -o claude -g claude -m 755 "$INIT_DIR"

NEED_INIT=true
if [ -f "$INIT_FLAG" ]; then
    EXISTING_ID="$(cat "$INIT_FLAG" 2>/dev/null || true)"
    if [ "$EXISTING_ID" = "$IMAGE_ID" ]; then
        NEED_INIT=false
        log "Init flag matches image $IMAGE_ID — skip auto qarko-init."
    else
        log "Image changed ($EXISTING_ID -> $IMAGE_ID) — re-run qarko-init."
    fi
fi

if "$NEED_INIT"; then
    log "Launching qarko-init in background as 'claude' (image=$IMAGE_ID)."
    # 디버깅: ENV_FILE 상태 기록
    log "ENV_FILE size=$(wc -c <"$ENV_FILE" 2>/dev/null || echo 0), lines=$(wc -l <"$ENV_FILE" 2>/dev/null || echo 0), GITHUB_TOKEN found=$(grep -c '^export GITHUB_TOKEN=' "$ENV_FILE" 2>/dev/null || echo 0)"
    # 상태/플래그/락 파일 전부 claude 소유로 시작 상태 기록
    install -o claude -g claude -m 644 /dev/null "$STATUS_FILE"
    su - claude -c "echo running > '$STATUS_FILE'"

    (
        # flock + 상태 파일 쓰기를 전부 su(claude) 컨텍스트에서 수행.
        # su - 가 login shell 이지만 -c 는 non-interactive 라 /etc/profile.d 자동
        # source 가 보장되지 않음 → 명시적 source 로 Railway env 확실히 로드.
        su - claude -c "
            set -eo pipefail
            [ -r /etc/profile.d/qarko-railway-env.sh ] && source /etc/profile.d/qarko-railway-env.sh
            echo \"[bg] GITHUB_TOKEN len=\${#GITHUB_TOKEN}\" >&2
            exec 200>'$LOCK_FILE'
            if ! flock -n 200; then
                echo '[entrypoint-bg] qarko-init already running (lock held)' >&2
                exit 0
            fi
            if /usr/local/bin/qarko-init; then
                echo '$IMAGE_ID' > '$INIT_FLAG'
                echo ok > '$STATUS_FILE'
            else
                rc=\$?
                echo \"failed rc=\$rc\" > '$STATUS_FILE'
                exit \"\$rc\"
            fi
        " && log "qarko-init complete (image=$IMAGE_ID)." \
          || log "ERROR: qarko-init failed — check $INIT_DIR/logs/"
    ) &
fi

# ── 6. 로그인 안내 (qarko-init 상태를 SSH 로그인 시 출력) ───────────────
cat > /etc/profile.d/qarko-init-status.sh <<'EOS'
# qarko-init 상태 안내 (SSH 로그인 시 표시)
if [ -f /home/claude/.qarko-init/status ]; then
    _qs="$(cat /home/claude/.qarko-init/status 2>/dev/null)"
    case "$_qs" in
        running)
            echo "[qarko-init] 복원 진행 중 — 완료 전 claude 실행 금지"
            echo "[qarko-init] 상태: watch -n2 'cat /home/claude/.qarko-init/status'"
            ;;
        failed*)
            echo "[qarko-init] 복원 실패: $_qs"
            echo "[qarko-init] 로그: ls -lt /home/claude/.qarko-init/logs/ | head"
            ;;
        ok)
            : ;;
    esac
    unset _qs
fi
EOS
chmod 644 /etc/profile.d/qarko-init-status.sh

# ── 7. sshd foreground — tini(PID 1)의 자식, sshd가 자기 자식 reap ───────
log "sshd starting in foreground on :22."
exec /usr/sbin/sshd -D -e
